module ReverseApp{
    interface Reverse{
        String reverseString(in string input);
        };

    };



1. idlj -fall ReverseString.idl

2.Compile All Java 
cd C:\Users\Shreya\workspace\ReverseStringCORBAProject
javac -d bin -cp src src\ReverseApp\*.java src\ReverseImpl.java src\ReverseServer.java src\ReverseClient.java

3.Start ORB Daemon (in new CMD)
orbd -ORBInitialPort 1050

4. Run the Server (in new CMD)
cd C:\Users\Shreya\workspace\ReverseStringCORBAProject
java -cp bin ReverseServer -ORBInitialPort 1050 -ORBInitialHost localhost

5. Run the Client (in new CMD terminal)
cd C:\Users\Shreya\workspace\ReverseStringCORBAProject
java -cp bin ReverseClient -ORBInitialPort 1050 -ORBInitialHost localhost
